apiVersion: v1
kind: Service
metadata:
  name: skillbridge-server-svc
  namespace: skillbridge
  labels:
    app: skillbridge-server
spec:
  type: ClusterIP
  selector:
    app: skillbridge-server
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      protocol: TCP
